### PR TITLE
refactor: fix overlapping button

### LINKED ISSUE #138: Overlapping on desktop in sendTransaction component
The `Copy` text is covered a little bit by the button in the `sendTransaction` component on desktop:

image

### PR DESCRIPTION
**Pull request by ImmanuelSegol**
closes #138

### CODE REVIEW

**Comment by ImmanuelSegol** [comment]
> The copy button is fine now but the ID is getting overlapped by the QR code:
> image

Im unable to reproduce this, attempted to make the id overlap on multiple screen sizes, what screen size are you using?
I added some margin around the id just to make it look better as it was very close to the QR code.

**Comment by michael1011** [comment]
@ImmanuelSegol I am using a screen with the size of: 3840 x 2160

**Comment by michael1011** [comment]
I allowed myself to make some minor layout changes and it looks fine for me:
image

This PR can be merged if you agree on the changes I made

**Comment by michael1011** [comment]
After my fix it also shows the message about the LTC address correctly: 
image

**Pull request merged**
